version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    assignees:
      - ascopes
    labels:
      - ci
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    assignees:
      - ascopes
    labels:
      - maven
