version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    assignees:
      - ascopes
    labels:
      - ci
      - housekeeping
  - package-ecosystem: maven
    directory: /
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: saturday
      time: "09:00"
    assignees:
      - ascopes
    labels:
      - maven
      - housekeeping
