version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: "weekly"
    assignees:
      - "ascopes"
    labels:
      - "ci"
      - "housekeeping"


  - package-ecosystem: "maven"
    directory: "/"
    open-pull-requests-limit: 99
    schedule:
      interval: "weekly"
    assignees:
      - "ascopes"
    labels:
      - "maven"
      - "housekeeping"


