version: 2
updates:
  - package-ecosystem: github-actions
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: saturday
    target-branch: main
    assignees:
      - ascopes
    labels:
      - ci
  - package-ecosystem: maven
    open-pull-requests-limit: 99
    rebase-strategy: auto
    schedule:
      interval: weekly
      day: saturday
    target-branch: main
    assignees:
      - ascopes
    labels:
      - maven
