name: Deploy a branch

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: "Dry run the deployment"
        default: true
        type: boolean

      skip-deploy:
        description: "Skip deployment step"
        default: false
        type: boolean

      skip-pages:
        description: "Skip page publishing step"
        default: false
        type: boolean

      skip-initial-verification:
        description: "Skip tests, dependency check, formatting, licenses"
        default: false
        type: boolean

      version:
        description: "Version (leave blank to release non-SNAPSHOT patch)"
        default: ""
        type: string

jobs:
  maven-central:
    name: Build and deploy code
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      id-token: write
      pages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - name: Initialize Java environment
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          # Must use >= JDK 17 for Javadocs to generate correctly.
          java-version: 17
          server-id: ossrh
          server-username: OSSRH_USERNAME
          server-password: OSSRH_TOKEN
          gpg-passphrase: GPG_PASSPHRASE
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}

      - name: Ensure all tests pass
        if: ${{ ! inputs.skip-initial-verification }}
        shell: bash
        run: >-
          ./mvnw 
          -B 
          -e
          -T4
          -U
          -P dependency-check
          --no-transfer-progress
          -Dstyle.color=always
          -Dmaven.wagon.httpconnectionManager.ttlSeconds=120
          clean verify

      - name: Configure Git
        shell: bash
        run: |-
          source ./scripts/common.sh
          
          info "Applying Git user configuration"
          run <<SCRIPT
            git config user.name '${{ github.actor }}'
            git config user.email '${{ github.actor }}@users.noreply.github.com'
          SCRIPT

      - name: Perform release to Maven Central
        shell: bash
        run: |-
          source ./scripts/common.sh
          
          info "Determining release version to use (this may take a moment)..."
          if [[ '${{ inputs.version }}' == "" ]]; then
            release_version="$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout | sed 's/-SNAPSHOT//g')"
          else
            release_version='${{ inputs.version }}'
          fi
          
          success "Will use version ${release_version} for this release"
          
          info "Preparing and performing the release"
          ensure-set OSSRH_USERNAME OSSRH_TOKEN GPG_PASSPHRASE
          
          build_args=(
            "-Dmaven.test.skip" 
            "-DskipTests"
            "-Dlicense.skip=true"
            "-Dcheckstyle.skip=true"
          )

          build_goals=()
          if [[ '${{ inputs.skip-deploy }}' == 'true' ]]; then
            build_goals+=("clean" "package" "javadoc:jar")
            build_goals+=("${build_args[@]}")
          else
            build_goals+=("release:prepare" "release:perform")
          fi
          
          run <<-SCRIPT          
            ./mvnw -B -e \
                --no-transfer-progress \
                -Darguments='${build_args[@]}' \
                -DdryRun='${{ inputs.dry-run }}' \
                -Dmaven.wagon.httpconnectionManager.ttlSeconds=120 \
                -Dpassword='${{ secrets.GITHUB_TOKEN }}' \
                -DreleaseVersion='${release_version}' \
                -DsignTag=false \
                -Dstyle.color=always \
                -Dtag='v${release_version}' \
                ${build_goals[@]}
          SCRIPT
          
          success "Release has been performed successfully"

        env:
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_TOKEN: ${{ secrets.OSSRH_TOKEN }}
          GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}

      - name: Upload JavaDocs as a build artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: java-compiler-testing/target/apidocs

      - name: Deploy JavaDocs build artifact to GitHub Pages
        if: ${{ ! inputs.dry-run }} && ${{ ! inputs.skip-pages }}
        id: deployment
        uses: actions/deploy-pages@v1
